[book]
authors = ["Kurt Pan"]
language = "en"
multilingual = false
src = "post"
title = "ZK Insights"

[preprocessor]


[output.html]
mathjax-support = true
no-section-label = true
default-theme = "light"
git-repository-url = "https://github.com/ZKPunk-Org/zk-insights"
git-repository-icon = "fa-github"


[output.html.fold]
enable = true # whether or not to enable section folding
level = 0     # the depth to start folding

[preprocessor.header-footer]
headers = [{ regex = ".*", padding = "Edited by <a href='https://zkpunk.pro'>ZKPunk</a>\n" }]
footers = [
    {regex = ".*",  padding = "<div style=\"text-align: center;\">🎉&nbsp;Supported by&nbsp;<a href=\"https://www.gccofficial.org/\">GCC</a>&nbsp;🎉</div>" }
]
