import Mathlib

/-!
# Finite-dimensional filtration stabilization

A finite algebra generated by affine coordinates is reached by a sufficiently
large bidegree rectangle: choose polynomial representatives of a finite
spanning set and take a common degree bound.  This file isolates the purely
linear-algebraic stabilization argument used in that step.
-/

namespace PHJFRI.Stage3.FiniteFiltrationSurjection

open Function

noncomputable section

variable {K Q : Type*} [Field K]
variable [AddCommGroup Q] [Module K Q]

/-- A finite set whose elements enter a monotone filtration one by one enters
    at one common stage. -/
theorem finite_eventual_mem
    (V : ℕ → Submodule K Q) (hmono : Monotone V)
    (S : Finset Q)
    (hcover : ∀ x ∈ S, ∃ n, x ∈ V n) :
    ∃ N, ∀ x ∈ S, x ∈ V N := by
  classical
  induction S using Finset.induction_on with
  | empty =>
      exact ⟨0, by simp⟩
  | @insert a S ha ih =>
      obtain ⟨na, hna⟩ := hcover a (Finset.mem_insert_self a S)
      have hcoverS : ∀ x ∈ S, ∃ n, x ∈ V n := by
        intro x hx
        exact hcover x (Finset.mem_insert_of_mem hx)
      obtain ⟨nS, hnS⟩ := ih hcoverS
      refine ⟨max na nS, ?_⟩
      intro x hx
      rcases Finset.mem_insert.mp hx with rfl | hxS
      · exact hmono (Nat.le_max_left _ _) hna
      · exact hmono (Nat.le_max_right _ _) (hnS x hxS)

/-- If a finite spanning set is eventually contained in a monotone sequence
    of submodules, then one stage is already the whole space. -/
theorem exists_eq_top_of_finite_spanning_cover
    (V : ℕ → Submodule K Q) (hmono : Monotone V)
    (S : Finset Q)
    (hspan : Submodule.span K (S : Set Q) = ⊤)
    (hcover : ∀ x ∈ S, ∃ n, x ∈ V n) :
    ∃ N, V N = ⊤ := by
  obtain ⟨N, hN⟩ := finite_eventual_mem V hmono S hcover
  refine ⟨N, top_unique ?_⟩
  rw [← hspan]
  exact Submodule.span_le.mpr fun x hx => hN x hx

/-- Range version: an increasing family of linear maps that eventually hits a
    finite spanning set contains a surjective member. -/
theorem exists_surjective_of_finite_spanning_cover
    (E : ℕ → Q →ₗ[K] Q)
    (hmono : Monotone fun n => LinearMap.range (E n))
    (S : Finset Q)
    (hspan : Submodule.span K (S : Set Q) = ⊤)
    (hcover : ∀ x ∈ S, ∃ n, x ∈ LinearMap.range (E n)) :
    ∃ N, Function.Surjective (E N) := by
  obtain ⟨N, htop⟩ := exists_eq_top_of_finite_spanning_cover
    (fun n => LinearMap.range (E n)) hmono S hspan hcover
  exact ⟨N, LinearMap.range_eq_top.mp htop⟩

/-- More general domain-indexed range version. -/
theorem exists_surjective_of_filtered_ranges
    (D : ℕ → Type*) [∀ n, AddCommGroup (D n)] [∀ n, Module K (D n)]
    (E : ∀ n, D n →ₗ[K] Q)
    (hmono : Monotone fun n => LinearMap.range (E n))
    (S : Finset Q)
    (hspan : Submodule.span K (S : Set Q) = ⊤)
    (hcover : ∀ x ∈ S, ∃ n, x ∈ LinearMap.range (E n)) :
    ∃ N, Function.Surjective (E N) := by
  obtain ⟨N, htop⟩ := exists_eq_top_of_finite_spanning_cover
    (fun n => LinearMap.range (E n)) hmono S hspan hcover
  exact ⟨N, LinearMap.range_eq_top.mp htop⟩

#print axioms finite_eventual_mem
#print axioms exists_eq_top_of_finite_spanning_cover
#print axioms exists_surjective_of_finite_spanning_cover
#print axioms exists_surjective_of_filtered_ranges

end

end PHJFRI.Stage3.FiniteFiltrationSurjection
