import Mathlib

/-!
# Two-generator Koszul syzygy core

For the bihomogeneous Koszul complex, exactness at the middle term reduces to
an elementary divisibility statement: if `P` has Euclid's property relative
to `Q`, every relation `P*A + Q*B = 0` is generated by `(Q,-P)`.

The statement is characteristic-free.  In the polynomial application the
Euclid hypothesis follows from absence of a common irreducible factor in the
UFD of bihomogeneous polynomials.
-/

namespace PHJFRI.Stage3.KoszulSyzygy

noncomputable section

variable {R : Type*} [CommRing R] [NoZeroDivisors R]

/-- Elementwise exactness of the two-generator Koszul complex under the one
    Euclid divisibility implication actually used by the proof. -/
theorem relation_generated_by_koszul
    (P Q A B : R)
    (hP : P ≠ 0)
    (hEuclid : ∀ x : R, P ∣ Q * x → P ∣ x)
    (hrel : P * A + Q * B = 0) :
    ∃ h : R, A = Q * h ∧ B = -(P * h) := by
  have hdiv : P ∣ Q * B := by
    refine ⟨-A, ?_⟩
    calc
      Q * B = -(P * A) := by linear_combination hrel
      _ = P * (-A) := by ring
  obtain ⟨c, hc⟩ := hEuclid B hdiv
  have hfactor : P * (A + Q * c) = 0 := by
    rw [hc] at hrel
    calc
      P * (A + Q * c) = P * A + Q * (P * c) := by ring
      _ = 0 := hrel
  have hsum : A + Q * c = 0 := by
    rcases mul_eq_zero.mp hfactor with hPzero | hsum
    · exact (hP hPzero).elim
    · exact hsum
  refine ⟨-c, ?_, ?_⟩
  · linear_combination hsum
  · rw [hc]
    ring

/-- Symmetric variant, useful when the available Euclid lemma is oriented
    toward `Q`. -/
theorem relation_generated_by_koszul_right
    (P Q A B : R)
    (hQ : Q ≠ 0)
    (hEuclid : ∀ x : R, Q ∣ P * x → Q ∣ x)
    (hrel : P * A + Q * B = 0) :
    ∃ h : R, A = Q * h ∧ B = -(P * h) := by
  have hdiv : Q ∣ P * A := by
    refine ⟨-B, ?_⟩
    calc
      P * A = -(Q * B) := by linear_combination hrel
      _ = Q * (-B) := by ring
  obtain ⟨c, hc⟩ := hEuclid A hdiv
  have hfactor : Q * (P * c + B) = 0 := by
    rw [hc] at hrel
    calc
      Q * (P * c + B) = P * (Q * c) + Q * B := by ring
      _ = 0 := hrel
  have hsum : P * c + B = 0 := by
    rcases mul_eq_zero.mp hfactor with hQzero | hsum
    · exact (hQ hQzero).elim
    · exact hsum
  refine ⟨c, hc, ?_⟩
  linear_combination hsum

#print axioms relation_generated_by_koszul
#print axioms relation_generated_by_koszul_right

end

end PHJFRI.Stage3.KoszulSyzygy
